services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.dev # Verweise auf das dev Dockerfile
    container_name: dev_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "${HOST_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Speichert Daten auch über Container-Neustarts hinweg

volumes:
  postgres_data:
